config/routes.rb
Rails.application.routes.draw do
  resources :skillsets
  resources :projects

  root to: 'home#index'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'delete_user_session'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  resources :users, only: [] do
    resources :projects
  end

  resources :users, only: [] do
    resources :skillsets
  end

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :project_skillsets
    has_many :skillsets, through: :project_skillsets
    
    validates :title, presence: true
    validates :genre, presence: true
    validates :info, presence: true
    validates :contact, presence: true

    scope :search, -> (query) { query ? Project.where("LOWER(title) LIKE ?", "%#{query.downcase}%") : Project.all }
    scope :featured_projects, -> {Project.last(2).collect {|project| "#{project.title}, Genre: #{project.genre}"}.join(" <br> ").html_safe}
end

app/models/project_skillset.rb
class ProjectSkillset < ApplicationRecord
    belongs_to :project 
    belongs_to :skillset
end

app/models/skillset.rb
class Skillset < ApplicationRecord
    belongs_to :user
    has_many :project_skillsets
    has_many :projects, through: :project_skillsets

    validates :name, presence: true
    validates :skills, presence: true
    validates :info, presence: true
    validates :contact, presence: true

    def self.search(query, user_id)
        if user_id
            user = User.find_by_id(user_id)
            query ? user.skillsets.where("LOWER(skills) LIKE ?", "%#{query.downcase}%") : user.skillsets 
        else
            query ? Skillset.where("skills LIKE ?", "%#{query}%") : Skillset.all
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :projects
    has_many :skillsets
    has_many :project_skillsets, through: :projects

    validates :email, presence: true, uniqueness: true
    has_secure_password

    def get_email
        self.email.gsub(/\@.*/, "")
    end

    def self.find_or_create_by_omniauth(auth)
        @user = User.find_by(email: auth["info"]["email"])
        if @user.uid.nil?
          @user.update(uid: auth["uid"])
        elsif @user.nil?
          @user = User.create_by(uid: auth["uid"]) do |u|
            u.email = auth["info"]["email"]
            u.password = SecureRandom.hex
          end
        end
        @user
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_logged_in?
  helper_method :current_user

  def redirect_if_not_signed_in
    redirect_to login_path unless is_logged_in?
  end

  def redirect_if_signed_in
    redirect_to projects_path if is_logged_in?
  end
  

  private
    def is_logged_in?
      !!session[:user_id]
    end

    def current_user
      User.find_by_id(session[:user_id]) if is_logged_in?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'home_layout'
    before_action :redirect_if_signed_in
    def index

    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :redirect_if_not_signed_in
  before_action :set_user
  before_action :set_project, except: [:index, :new, :create]

  def index
    @projects = Project.search(params[:query])
  end

  def new
    @project = Project.new
  end
  
  def create
    @project = @user.projects.build(project_params)
    if @project.save
      redirect_to projects_path
    else
      flash[:notify] = @project.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to projects_path unless current_user == @project.user
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      flash[:notify] = @project.errors.full_messages
      render :edit
    end
  end

  def destroy
    if current_user == @project.user
    @project.destroy
    else 
      flash[:alert] = "You are not authorized to do that"
    end
    redirect_to projects_path
  end

  private

    def set_user
      @user = User.find_by_id(params[:user_id])
    end

    def set_project
      @project = Project.find_by_id(params[:id])
    end


    def project_params
      params.require(:project).permit(:title, :genre, :info, :contact, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    layout 'home_layout'
  
    before_action :redirect_if_signed_in, except: [:destroy]
  
    def new
      @user = User.new
    end
  
    def create 
      if auth
        @user = User.find_or_create_by_omniauth(auth)
        session[:user_id] = @user.id
        redirect_to projects_path
      else
        @user = User.find_by(email: user_params[:email])
        if @user && @user.authenticate(user_params[:password])
          session[:user_id] = @user.id
          redirect_to projects_path
        else
          render :new
        end
      end
    end
  
    def destroy
      session.clear
      redirect_to root_path
    end
  
    private
      def user_params
        params.require(:user).permit(:email, :password)
      end

      def auth
        request.env['omniauth.auth']
      end
  end

app/controllers/skillsets_controller.rb
class SkillsetsController < ApplicationController
    before_action :redirect_if_not_signed_in
    before_action :set_user
    before_action :set_skillset, except: [:index, :new, :create]
  
    def index
      @skillsets = Skillset.search(params[:query], params[:user_id])
    end
  
    def new
      @skillset = Skillset.new
    end
    
    def create
      @skillset = @user.skillsets.build(skillset_params)
      if @skillset.save
        redirect_to skillsets_path
      else
        flash[:notify] = @skillset.errors.full_messages
        render :new
      end
    end
  
    def show
    end
  
    def edit
      redirect_to skillsets_path unless current_user == @skillset.user
    end
  
    def update
      if @skillset.update(skillset_params)
        redirect_to skillset_path(@skillset)
      else
        flash[:notify] = @skillset.errors.full_messages
        render :edit
      end
    end
  
    def destroy
      if current_user == @skillset.user
      @skillset.destroy
      end
      redirect_to skillsets_path
    end
  
    private
  
      def set_user
        @user = User.find_by_id(params[:user_id])
      end
  
      def set_skillset
        @skillset = Skillset.find_by_id(params[:id])
      end
  
      def skillset_params
        params.require(:skillset).permit(:name, :skills, :info, :contact, :user_id)
      end
end

app/controllers/users_contoller.rb
class UsersController < ApplicationController
    layout 'home_layout'
    before_action :redirect_if_signed_in
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_blogs_path(@user)
      else
        render :new
      end
    end
  
    private
      def user_params
        params.require(:user).permit(:email, :password)
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    layout 'home_layout'
    before_action :redirect_if_signed_in
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_projects_path(@user)
      else
        flash[:notify] = @user.errors.full_messages
        render :new
      end
    end
  
    private
      def user_params
        params.require(:user).permit(:email, :password)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def render_project_errors
        if !@project.errors.empty?
          @project.errors.full_messages.each do |msg|
            msg
          end.join(" ")
        end
      end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skillsets_helper.rb
module SkillsetsHelper
end

app/views/home/index.html.erb
<body class="epic sticky">
<main class="stickier">
<div class="rad">
<h1 class="center thin">Welcome to SymbioSound</h1>
<h4 class="blue-grey-text text-darken-2 center thin">A collaborative music network </h4>
<hr width="400px">
<h5 class="blue-grey-text text-darken-2 center thin">Today's featured projects: </h5>
<p class="blue-grey-text text-darken-2 center thin"><%= Project.featured_projects %> </p>
<h4 class="blue-grey-text text-darken-2 center thin">Please <%= link_to "Login", login_path %> or <%= link_to "Signup", signup_path %></h4>
</div>
<!--<img class="responsive-img" src="symbiosoundbg.jpeg">-->
<!--<h5 class="center thin"><%= link_to "Login With Facebook", "/auth/facebook" %></h5>-->
</main>
</body>

app/views/layouts/_errors.html.erb
<% if flash[:error] || flash[:success] || flash[:notice] || flash[:warning] %>
  <div class="errors">
    <ul>
      <% if flash[:error] %>
      <li><%= flash[:error] %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<body class="stickier">
<main class="sticky">
<footer class="page-footer red lighten-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text thin">SymbioSound</h5>
        <p class="grey-text text-lighten-4 thin"></p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text thin">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3 thin" href="https://www.instagram.com/">Instagram</a></li>
          <li><a class="grey-text text-lighten-3 thin" href="https://www.facebook.com/">Facebook</a></li>
          <li><a class="grey-text text-lighten-3 thin" href="https://www.twitter.com/">Twitter</a></li>
          <li><a class="grey-text text-lighten-3 thin" href="#!">About</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2019 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">A Top Shelf Sound affiliate</a>
    </div>
  </div>
</footer>
</main>
</body>

app/views/layouts/_nav.html.erb
<nav class="red lighten-2">
  <div class="container">
    <%= link_to "SymbioSound", root_path, class: "brand-logo thin" %>
    <ul class="right">
      <% if is_logged_in? %>
        <li class="thin"><%= link_to "Project List", projects_path %></li>
        <li class="thin"><%= link_to "New Project", new_user_project_path(current_user) %></li>
        <li class="thin"><%= link_to "Skillset List", skillsets_path %></li>
        <li class="thin"><%= link_to "New Skillset", new_user_skillset_path(current_user) %></li>
        <li class="thin"><%= link_to "Logout", delete_user_session_path, method: 'delete' 
        %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SymbioSound</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SymbioSound</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/errors' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_form.html.erb
<ul>
    <%if !@project.errors.empty? %>
      <%@project.errors.full_messages.each do |msg|%>
         <li class="red-text"><%= msg %></li>
        <%end%>
      <%end%>
</ul>
<%= form_for [user, project] do |f| %>
<%= f.hidden_field :user_id, value: user.id %>
    <div class="input-field">
      <%= f.text_field :title %>
      <%= f.label :title %>
    </div>

    <div class="input-field">
      <%= f.text_field :genre %>
      <%= f.label :genre %>
    </div>

    <div class="input-field">
        <%= f.text_field :contact %>
        <%= f.label :contact %>
     </div>

  
    <div class="input-field">
      <%= f.text_area :info, class: "materialize-textarea" %>
      <%= f.label :info %>
    </div>
  
    <%= f.submit button_name, class: "btn red lighten-2" %>



  <% end %>

app/views/projects/_project.html.erb
<tr>
    <td><%= link_to project.title, project_path(project) %></td>
    <td><%= project.genre %></td>
    <td><%= link_to "Edit", edit_user_project_path(current_user, project) %></td>
    <td><%= link_to "Delete", project_path(project), method: "delete" %></td>
</tr>

app/views/projects/edit.html.erb
<h3 class="thin">Edit your Project</h3>
<%= render partial: "form", locals: { project: @project, user: @user,  button_name: "Edit Project" } %>

app/views/projects/index.html.erb
<h5 class="center thin">Hitting a deadend on a promising song?</h5>
<h5 class="center thin">Looking to start a band?</h5>
<h5 class="center thin">Interested in collaborating with someone new?</h5>
<h3 class="center thin">Check out our list of projects</h3>
<%= form_tag user_projects_path(current_user), method: "get" do %>
    <%= text_field_tag :query.downcase %>
    <%= submit_tag :search, class: "btn red lighten-2" %>
  <% end %>
  <table class="thin table" align="center">
    <thead>
      <tr>
        <th>Title</th>
        <th>Genre</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <%= render @projects %>
  </table>

app/views/projects/new.html.erb
<h3 class = "thin">Create a Project</h3>
<%= render partial: "form", locals: { project: @project, user: @user, button_name: "Create Project"} %>

app/views/projects/show.html.erb
<h3 class="thin"><%= @project.title %></h3>
<font size="2" class="thin"> <%= @project.created_at.strftime("%B %d, %Y") %></font><br><br>
<div class="card-panel  ">
<h5 class="thin">Genre: <%= @project.genre %></h2><br>
<font size="3" class="thin">More info: <%= @project.info %></font><br><br>
</div>
<font size="3" class="thin">Created by user: <%= link_to @project.user.get_email, user_skillsets_path(@project.user_id) %></font><br>
<font size="3" class="thin">Contact: <%= @project.contact %></font><br><br><br>
<% unless current_user == @project.user %>
<%= form_tag user_skillsets_path(current_user), method: "get" do %>
    <%= submit_tag "Pair a Skillset", class: "btn blue-grey darken-1" %>
  <% end %>
<%end %>

app/views/skillsets/_form.html.erb
<ul>
    <%if !@skillset.errors.empty? %>
      <%@skillset.errors.full_messages.each do |msg|%>
         <li class="red-text"><%= msg %></li>
        <%end%>
      <%end%>
</ul>
<%= form_for [user, skillset] do |f| %>
<%= f.hidden_field :user_id, value: user.id %>
    <div class="input-field">
      <%= f.text_field :name %>
      <%= f.label :name %>
    </div>

    <div class="input-field">
      <%= f.text_field :skills %>
      <%= f.label :skills %>
    </div>

    <div class="input-field">
        <%= f.text_field :contact %>
        <%= f.label :contact %>
     </div>
  
    <div class="input-field">
      <%= f.text_area :info, class: "materialize-textarea" %>
      <%= f.label :info %>
    </div>
  
    <%= f.submit button_name, class: "btn red lighten-2" %>
  <% end %>

app/views/skillsets/_skillset.html.erb
<tr>
    <td><%= link_to skillset.name, skillset_path(skillset) %></td>
    <td><%= skillset.skills %></td>
    <td><%= link_to "Edit", edit_user_skillset_path(current_user, skillset) %></td>
    <td><%= link_to "Delete", skillset_path(skillset), method: "delete" %></td>
</tr>

app/views/skillsets/edit.html.erb
<h3 class="thin">Edit your Skillset</h3>
<%= render partial: "form", locals: { skillset: @skillset, user: @user,  button_name: "Edit Skillset" } %>

app/views/skillsets/index.html.erb
<h1 class="center thin">List of Skillsets</h1>
<%= form_tag skillsets_path, method: "get" do %>
    <%= text_field_tag :query %>
    <%= submit_tag :search, class: "btn red lighten-2" %>
  <% end %>
  
  <table class="thin">
    <thead>
      <tr>
        <th>Name</th>
        <th>Skills</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <%= render @skillsets %>
  </table>

app/views/skillsets/new.html.erb
<h3 class="thin">Create a Skillset</h3>
<%= render partial: "form", locals: { skillset: @skillset, user: @user, button_name: "Create Skillset"} %>

app/views/skillsets/show.html.erb
<h3 class="thin"><%= @skillset.name %></h3>
<font size="2" class="thin"> <%= @skillset.created_at.strftime("%B %d, %Y") %></font><br><br>
<div class="card-panel text-lighten-5">
<h5 class="thin">Skills: <%= @skillset.skills %></h2><br>
<font size="3" class="thin">More info: <%= @skillset.info %></font><br><br>
</div>
<font size="3" class="thin">Created by user: <%= @skillset.user.get_email %></font><br>
<font size="3" class="thin">Contact: <%= @skillset.contact %></font><br>

app/views/users/new.html.erb
<body class="epic sticky">
<main class="stickier">
<h1 class="thin">Signup</h1>

<%= render partial: "sessions/form", locals: { user: @user, button_name: "Signup", session_form_path: signup_path, method: "post" } %>
<p><%= link_to "Have an account? Login", login_path, class: "btn red lighten-2" %></p>
</main>
</body>